### ISSUE TITLE
Kiwami 2 - No es posible reconstruir algunas de las imágenes extraídas

### ISSUE THREAD

**Issue by MaybeDaveyy** [Kaplas80/TF3#52]
**Hola Kaplas! Hoy traduje una de las imágenes que venían junto a la extracción, y al intentar reconstruir me encontré con el siguiente error:**

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at TF3.YarhlPlugin.YakuzaCommon.Converters.Par.Writer.Convert(NodeContainerFormat source)
   at Yarhl.FileFormat.ConvertFormat.With(IConverter converter, Object src)
   at TF3.Core.Helpers.YarhlNodeExtension.ApplyChange(Node node, ConverterMetadata metadata, Object[] parameters) in /_/src/Libraries/TF3.Core/Helpers/YarhlNodeExtension.cs:line 94
   at TF3.Core.Helpers.YarhlNodeExtension.Transform(Node node, List`1 converters, List`1 parameters) in /_/src/Libraries/TF3.Core/Helpers/YarhlNodeExtension.cs:line 69
   at TF3.Core.GameScript.WriteContainers(List`1 containers, Node parent) in /_/src/Libraries/TF3.Core/GameScript.cs:line 266
   at TF3.Core.GameScript.Rebuild(String gamePath, String translationPath, String outputPath) in /_/src/Libraries/TF3.Core/GameScript.cs:line 201
   at TF3.CommandLine.Program.Rebuild(RebuildOptions options) in /_/src/Apps/TF3.CommandLine/Program.cs:line 184
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TF3.CommandLine.Program.Main(String[] args) in /_/src/Apps/TF3.CommandLine/Program.cs:line 41

Después de investigar por un rato, logré descubrir el origen del error: son dos pngs que causaban esos problemas, si al menos uno se encontraba en la carpeta de reconstrucción, el error aparecía. Este error no sucede con los demás pngs.

### Los pngs problemáticos son
otr_clan_param_04.png
attack_grade_5.png

PD: Probé con todas las imágenes excepto algunas como las letras de las canciones del karaoke.

**Comment by Kaplas80** [comment]
Es raro, porque en su momento probé a extraer todas las imágenes y después reempaquetarlas y no me dio problema. ¿Te falla incluso con las imágenes originales? ¿Puede ser que estuviesen abiertas por algún otro programa (o el antivirus) a la hora de reconstruir?

**Comment by MaybeDaveyy** [comment]
Intenté extrayendo todo de nuevo y reconstruirlo, pero aun así el error persiste.

Cabe destacar que para la extracción utilicé un backup de la carpeta del juego sin modificar; copiado justo después de descargarlo de Steam.
